### ISSUE TITLE
bug: named stack lambda runtime error

### ISSUE THREAD

**Issue by pgte** [architect/architect#1322] opened 2022-03-01 19:36 UTC
**Describe the issue**
After deploying with a specific name (using the `--name` CLI option), the deployed lambdas don't work and yield this error on the console instead:

```js

{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "AccessDeniedException: User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
    "reason": {
        "errorType": "AccessDeniedException",
        "errorMessage": "User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
        "code": "AccessDeniedException",
        "message": "User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
        "time": "2022-03-01T19:22:40.300Z",
        "requestId": "d21f1976-894f-4bb9-8eb7-7453bd898902",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 74.19124814886911,
        "stack": [
            "AccessDeniedException: User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
            "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
            "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
            "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
            "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: AccessDeniedException: User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at process.emit (domain.js:475:12)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}
```

It looks that there is an access problem trying to access a parameter, but I'm not sure why..

I'm using @architect/architect@10.0.2 and @architect/deploy@4.0.3.

[Here is a link to the generated sam file](https://gist.github.com/pgte/63659a1450e0ab6ba4e2de61452e00d5) if you find that useful.

**Comment by pgte** [comment] 2022-03-01 19:39
I was using @architect/architect@8.6.0 and this was not happening. Not sure if helpful...

**Comment by ryanblock** [comment] 2022-03-01 21:19
Hey @pgte: good news, this issue was reported yesterday in the [Arc Discord](https://discord.com/invite/y5A2eTsCRX) – I've got it reproducing [via this repo](https://github.com/Lugana707/test-architect-app-name-for-v10) courtesy of @lugana707. It is indeed a bug, and think we should have a fix probably by EOD. Please stand by!

**Comment by ryanblock** [comment] 2022-03-01 23:03
Fix for this is now out in Arc 10.0.3 + `@architect/functions` 5.0.4, thanks for your patience, y'all!

**Closed by ryanblock** 2022-03-01 23:03 UTC
Labels: bug

**Comment by pgte** [comment] 2022-03-02 09:34
@ryanblock I'm still getting the same error after updating and redeploying...

**Comment by pgte** [comment] 2022-03-02 09:38
The error this time is:

```js
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "AccessDeniedException: User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
    "reason": {
        "errorType": "AccessDeniedException",
        "errorMessage": "User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
        "code": "AccessDeniedException",
        "message": "User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
        "time": "2022-03-02T09:27:53.880Z",
        "requestId": "6024b134-7125-4311-9243-579b01fe892f",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 2.8452224650854063,
        "stack": [
            "AccessDeniedException: User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
            "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
            "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
            "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
            "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
            "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
            "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
            "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: AccessDeniedException: User: arn:aws:sts::974894071214:assumed-role/DecipadBackendStaging943-Role-1M2SYTSZGLP1B/DecipadBackendStaging943-PostApiAuthSigninProvider-cacbKgjHtgdx is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:eu-west-2:974894071214:parameter/DecipadBackendStaging because no identity-based policy allows the ssm:GetParametersByPath action",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at process.emit (domain.js:475:12)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}
```

[And here is the generated sam.yaml file](https://gist.github.com/pgte/7efc8ab071942789b18bfa5950e51e3b).

**Comment by ryanblock** [comment] 2022-03-02 13:48
You may need to reinstall Arc; this fix relies on a patch to a second order dependency.

**Comment by pgte** [comment] 2022-03-02 18:49
This sam file and deployment was generated by a Github action. Just to be sure I disabled `yarn` cache.
The [yarn.lock file looks like this](https://gist.github.com/pgte/e36fd59eb8e423525de5e70d0590b9d7).

@ryanblock can you tell me the dependency and the version this fix depends on?

**Comment by ryanblock** [comment] 2022-03-02 19:00
Yeah, it needs `@architect/package` 8.0.1. Patches are:
- https://github.com/architect/package/commit/7735df9f3d9ca02eed024ff6982b6fa072440bb1#diff-cb34fb351db17b025a3b5d4372d1a7b79e24f047db76efb42692b36c766f3c83
- https://github.com/architect/functions/commit/70f588e73f20d893d7f28a5794ca931b0b89709f#diff-4fec077d40b8548d1ae73f954bbee16455ffee230b68d23cd89cdb686ce1b204

**Comment by ryanblock** [comment] 2022-03-02 19:07
Looked at the gist, the issue is L344, it's specifying 8.0.0.

**Comment by pgte** [comment] 2022-03-02 19:47
I pinned the resolution (using the `resolution` entry in `package.json`) of `@architect/package` to that version or above and it fixed this.
@ryanblock awesome, thanks so much!
