### ISSUE TITLE
Long running function which resolves early continues execution even after timeout

### ISSUE THREAD

**Issue by andybee** [architect/architect#1137] opened 2021-05-03 16:46 UTC
**Describe the issue**
If you write a function which resolves, but continues to perform additional work, that work will continue to execute even after timeout.

**Steps to reproduce**
1. Checkout my [example project](https://github.com/andybee/arc-invoke-lambda-issue/blob/main/package.json).
2. Run `npm run event`.
3. After 5s, the file `/tmp/foo` is written, despite the event function timeout being set to 1s.

**Expected behavior**
Either when the promise resolves or timeout (whichever is sooner), the child process should be terminated (if it doesn't itself?)

**Comment by andybee** [comment] 2021-05-03 17:54
As an additional point, the event function that originally led myself down this path didn't have a timeout configured so defaulted to 5s, so was being terminated early. It would be really useful if Sandbox outputted something along the lines of "Function terminated after Xs timeout" rather than "Completed" to make it obvious what's occurring.

**Comment by filmaj** [comment] 2021-05-04 18:49
Got a PR up to handle a few cases similar to your repro over here: https://github.com/architect/sandbox/pull/571

Note that the tests in my PR are not identical to your event implementation @andybee. In fact, the way the event in your repro repo is built, sandbox won't be able to ever prevent the callback within from executing. This is because the event handler is `async`, but includes a `setTimeout` inside of it. If you execute that event handler as a standalone process, it will report completing before the timeout triggers.

I recommend either dropping `async` from the event handler definition (in which case sandbox can correctly detect it timing out since the event loop of the sync handler waits for the timeout to trigger), or `await` on a timeout inside the `async` event handler. Both of these two cases I described I added as integration tests in the PR I linked to above.

**Comment by andybee** [comment] 2021-05-04 20:32
I get we can't stop the report of "completion", but is there no way to kill the task when the Promise resolves (although admittedly having to handle the fact it might already not be there if it did genuinely exit cleanly)?

Obviously the demo is a silly example and not something I'd ever actually want to do, but I figure trying to stop this behaviour was a good idea in case someone accidentally codes up a very long running function within async that somehow resolves early, sandbox reports it complete, but it's actually still "silently" churning away even after Sandbox is terminated.

**Comment by filmaj** [comment] 2021-05-04 20:38
I will try to play around with the particular async-function-with-a-settimeout-within-it to see what more can be done. I'm not sure why the process running the async function emits an `exit` event even though the settimeout is still waiting inside of it...

**Comment by filmaj** [comment] 2021-05-08 11:10
So @ryanblock and I reviewed the PR open for this yesterday and turns out, actually, we _are_ able to handle the particular situation in your repro case, @andybee! I just added a test to the sandbox repo now for it.

We switched up the way we invoke (and subsequently kill) lambda functions locally such that, as soon as we detect that the lambda process has completed (via an involved process-wrapping-and-stdout-inspecting invocation method), we kill the process explicitly. It's this murder-first approach, in comparison to the wait-for-the-process-to-finish approach previously, that is able to handle lambda functions that are both async and use a settimeout within.

**Comment by ryanblock** [comment] 2021-05-11 03:13
Merged! Will let @filmaj make the call on whether to release now or with the other upcoming changes to Sandbox.

**Closed by ryanblock** 2021-05-11 03:13 UTC

**Comment by ryanblock** [comment] 2021-06-23 17:35
Just for reference should the example repo be destroyed at some point in the future, the offending reproducing `@event` Lambda in question:
```
const fs = require('fs');

exports.handler = async () => {
  const writeStream = fs.createWriteStream('/tmp/foo');
  setTimeout(() => {
    writeStream.write('hiya');
    writeStream.end();
  }, 5000);
};
```
