### ISSUE TITLE
static proxy at root not working for global installs

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#476] opened 2019-10-10 15:36 UTC
as of `6.0.13`

1. clone `https://github.com/andybee/arc-static`
2. `arc sandbox`

<img width="300" alt="Screen Shot 2019-10-10 at 11 34 16 AM" src="https://user-images.githubusercontent.com/990/66583831-e093f680-eb38-11e9-8075-027862c95237.png">

workaround here: 
https://gist.github.com/brianleroux/9fc2bcb29f96a29022ac918385727f1e

(going to duplicate this bug for folks looking for a fix in the architect/architect repo)

**Comment by ryanblock** [comment] 2019-10-11 17:36
Dupe of https://github.com/architect/sandbox/issues/92, fixed in `6.0.14`

**Closed by ryanblock** 2019-10-11 17:36 UTC
Labels: bug
