### ISSUE TITLE
Simple Queue Service not working

### ISSUE THREAD

**Issue by herschel666** [architect/architect#372] opened 2019-04-29 20:33 UTC
Hi. I'm trying to set up [a very simple SQS PoC](https://github.com/herschel666/arc-queue-test), that consists of two functions:

1. a `GET /` function, that publishes an SQS event
2. the queue function, that logs the payload

The functions and the queue are set up correctly (afaict), but when I visit the `/` endpoint, it errors with: `AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist or you do not have access to it.`

The stack trace is:

```
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:47:29)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

I dind't find any example online and I'm pretty much clueless what's the issue here… :-/

**Comment by brianleroux** [comment] 2019-05-07 22:03
Hmm. I was unable to reproduce this. Worked both locally and deployed for me. =( 

Can you give me more details on your env?

**Comment by brianleroux** [comment] 2019-05-09 23:18
closing for now as _I think_ things are working but pls reopen if you reproduce! 🙏

**Closed by brianleroux** 2019-05-09 23:18 UTC
Labels: triage
