### ISSUE TITLE
Architect icon similarity to the so-called Identitarians' emblem

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1071] opened 2021-02-16 17:19 UTC
Content warning: if you're uncomfortable with strong language, especially when used in the context of speaking out against racists and fascists, you should stop reading now. (You'd also be best advised to leave the Architect community, tbh, because around these parts, we will punch a nazi.)

Yesterday someone on Twitter [alerted us](https://twitter.com/sebs303/status/1361348946011058178) that the Architect logo bears a resemblance to the emblem of the so-called Identitarian movement. 

As an American, I hadn't heard of the Identitarians until yesterday (nor had any of the other Americans I immediately showed this around to). If, like me, you're unfamiliar, here's the tl;dr: the Identitarians are chiefly European far-right extremist movement focused on totally passé pseudointellectual racist bullshit justifing white supremacy, fascism, ethnic purging, and the usual list of hateful, repugnant trash.

For Americans, you can think of them as the European counterpart to the so-called "alt-right" – basically just rebranded, hipsterized nazi pap. (Additional reading below.)

Some time roughly around 2016-2017 by my estimation, these people chose as their emblem an encircled upwards facing arrow, reminiscent of a capital lambda, in black set on yellow, or vice versa. The apparent – and specious – intent is referencing the Battle of Thermopylae, because this type of pasty shit-for-brain loser, certainly without a single ab among their lot, think [cosplaying Zach Snyder action movies](https://newrepublic.com/article/154563/sparta-myth-rise-fascism-trumpism) will sufficiently mask their deep sense of inadequacy enough to further an agenda of white supremacy.

For hopefully obvious reasons, I'll not be presenting their imagery here – if you'd like to compare any visual similarities, please see the links at the bottom of this issue.

On the other hand sits the Architect logo, designed by our longtime friend and colleague, Amber Costley – truly one of the kindest, most wonderful humans I know. As I recall, of the many logo candidates she produced, we loved this icon's design both visually and for its intentions and themes:
- References both the A of Architect, and Lambda (because, you know, AWS Lambda has remained a core service managed by Architect)
- An upward-pointing arrow, signaling growth, optimism, and progress
- Encircled to imply a simple, pleasant wholeness, togetherness, and sturdiness
- In addition, it also had the bonus of referencing the Begin logo (2016), as the Architect project was spun out of Begin in 2017

The Architect logo is usually in white set on dark gray (but sometimes inverted).

<img src="https://user-images.githubusercontent.com/200964/108097362-e35d0080-7036-11eb-91c7-1f0a41368397.png" width=600>

None of the core maintainers, original authors, or folks involved in the logo design process of Architect had any idea about the Identitarians until yesterday – but now that we do, we are faced with a choice of how to respond:

- **Completely change the Architect icon**: put as much distance as possible between our visual identity and theirs; basically, just let them have the icon and move on.
- **Explore altering the Architect icon**: retain much of the core theme of the logo, but attempt some changes that differentiate the visual identities; an example (that probably won't work well): rotate our logo 45 degrees.
  - Obligatory note: as someone with a long history in design, I'd like to state that this option is least likely to work – logos contain a bit of visual magic, and can rarely be altered while retaining their core characteristics, recognizability, etc. I mention this option because I know other folks will, but imo this is unlikely to result in a satisfactory outcome.
- **Leave the Architect icon as-is**: make those dipshits share their symbol of their racist ideology with a bunch nerds, many or most of whom are liberal and anti-fascist, writing open source software named after [silly fictional animals](https://blog.begin.com/architect-8-3-custom-file-paths-much-more-a51def83817e).
  - Worth noting: not changing the logo doesn't mean we do nothing; perhaps we add a page to our site explaining our logo's background, and why we resoundingly reject Identitarians and all racist, fascist ideologies. And Beginner Corp (begin.com) and individuals in the Architect community will proudly (continue to) donate to progressive causes.

We'd very much appreciate your thoughts, ideas, and feedback! 💕🌈

---

Sources
- https://www.adl.org/education/references/hate-symbols/identitarian-lambda
- https://www.economist.com/europe/2016/11/12/meet-the-ib-europes-version-of-americas-alt-right
- https://en.wikipedia.org/wiki/Identitarian_movement

**Comment by brianleroux** [comment] 2021-02-17 23:37
closing duplicate of #1072

**Closed by brianleroux** 2021-02-17 23:37 UTC

**Comment by ryanblock** [comment] 2021-02-17 23:39
Lol. My internet connection was acting wonky at that moment, guess I must have posted twice!

**Comment by ajcwebdev** [comment] 2021-02-17 23:39
This is a tough one, and something that Tom came across back when Redwood was called Hammer, apparently the iconography of Thor's hammer has similar connotations now.

I'd vote for altering the logo to try to make it distinct while holding on to the personality of it, cause it shows you're aware of the issue and want to make a show of good faith. In my personal opinion, for what it's worth, changing the logo entirely is letting the terrorists win.
