### ISSUE TITLE
`npx sandbox` will fail silently if ~/.aws/credentials is missing

### ISSUE THREAD

**Issue by mikemaccana** [architect/architect#391] opened 2019-06-04 11:21 UTC
**Describe the bug**

**To Reproduce**
1. Make the hello world app on https://arc.codes/quickstart/install
 without doing the prerequisites (or just rename your .aws/credentials file)

2. Run `npx sandbox`

**Expected behavior**
The sandbox works (AWS credentials shouldn't bee needed locally) 

or

If AWS credentials are needed for the sandbox for some reason, an error should be displayed.

**Screenshots**

What happens instead: 

![image](https://user-images.githubusercontent.com/172594/58875327-250f1180-86c3-11e9-9345-961c0629a62c.png)

**Desktop (please complete the following information):**
Windows 10, arc 5.9.2

**Comment by ryanblock** [comment] 2019-06-06 21:43
Hmm, this isn't reproducing locally (on a Mac). Maybe it's a Windows issue, hard to say.

If you have a credentials file, `sandbox` starts?

**Comment by ryanblock** [comment] 2019-06-24 19:57
Just to followup, this should be partly fixed in `5.9.11`, but I think you'll still see this issue though. It looks like you've defined `@aws profile default` in your .arc; this will attempt to load your `~/.aws/credentials` `[default]` profile, and will hang if it's not present. In the mean time, if possible don't use `@aws profile` if you don't have a credentials file on your machine; if you must, feel free to write in a dummy credentials file with dummy keys prior to starting `sandbox`.

**Comment by ryanblock** [comment] 2019-06-24 19:58
Closing this in favor of #382

**Closed by ryanblock** 2019-06-24 19:58 UTC

**Comment by ryanblock** [comment] 2019-06-24 21:30
Followup: should now be resolved in `5.9.12`!
