### ISSUE TITLE
Customize ApiGateway Templates

### ISSUE THREAD

**Issue by ecwillis** [architect/architect#393] opened 2019-06-05 06:31 UTC
Would there be a way, or rather should there be a way to customize the `.vtl` templates that make up the API gateway deployments?

(Found here: https://github.com/architect/architect/blob/master/src/create/aws/create-http-route/create-route/_request.vtl)

I have a need to get a string representation of the request body back as it was submitted (not parsed) and In order to accomplish that I had to manually modify the API gateway as far as I can tell.

**Comment by ryanblock** [comment] 2019-06-05 20:47
Hey! vtl templates aside for a moment, can you be a bit more specific about what behavior you're seeing in Architect, and you're expecting?

**Comment by ecwillis** [comment] 2019-06-06 19:46
I am trying to accomplish a verification of a signed post request from a webhook service. The signature is an `HMAC` hash of the request body with a shared secret.

Since the body of the request is translated inside api gateway the original body is lost when it gets to the lambda so when I run the hash algorithm, the results are different (using something like `JSON.stringify` to recreate the body string.)

What I need is for the `rawBody` or the original body of the request to be passed through to the function.

**Comment by ryanblock** [comment] 2019-06-06 20:43
Hmm, that may depend on the format of the post and its reproducibility, but it sounds like you're describing a JSON API, that works great with HMAC signing. I actually did an implementation of HMAC signing recently, it's been great. Here's a code snippet derived from the impl I did with [GH's webhook signing](https://developer.github.com/webhooks/#delivery-headers):
```js
let arc = require('@architect/functions') // Not necessary for HMAC signing, just convenient!
let crypto = require('crypto')

exports.handler = arc.http(auth)

function auth (req, res) {
  let headers = req.headers
  let secret = 'whatever' // Shared with GitHub webhook
  let hmac = crypto.createHmac('sha1', secret)
  hmac.update(JSON.stringify(req.body))
  let sig = `sha1=${hmac.digest('hex')}` // Their signature begins with `sha1=`, ymmv
  if (headers['X-Hub-Signature'] === sig) {
    res({
      type: 'application/json; charset=utf-8;',
      body: {ok:true}
    })
  }
  else {
    res({
      status: 403,
      type: 'application/json; charset=utf-8;',
      body: {ok:false}
    })
  }
}
```

So tl;dr: what you're describing is absolutely possible! More importantly: Arc's body handling is not munging data on the way in, we present it as raw as API Gateway allows us to; the deeper feature request (customizing APIG's ingress data formats and such) is sadly significantly more challenging than one might think, and would necessarily break things for the rest of the system. But in this case that shouldn't be of concern, because what you want to do should be perfectly possible.

**Comment by ecwillis** [comment] 2019-06-06 20:56
Interesting ... 

I brought this up because I did a similar thing utilizing Shopify's verification method (https://help.shopify.com/en/api/getting-started/webhooks) and `JSON.stringify` and the hashes came out differently. I didn't dive too deeply into how the original body looked, but I assume that it's possible that the Shopify body and the `JSON.stringify` differed slightly, possibly in a newline or formatting situation.

I got around it by editing the `.vtl` in the console like this:

```
## Version 2.0.2
##
#set($rawBody = $input.body)      // Setting the Base64 encoded body here
#set($inputJson = $util.base64Decode($input.json('$')))
#if($inputJson.isEmpty())
  #set($body = "{}")
#else
  #set($body = $inputJson)
#end
##
{
  "body": $body,
  "rawBody": $rawBody,   // Added to the response
```

And in my function, I computed the hash like this:

```
const buf = Buffer.from(req.rawBody, 'base64');
const hash = crypto.createHmac('sha256', shopifyHookSecret).update(buf).digest('base64');
```

And that created a hash that was the same.

I may play around again with the JSON.stringify to make sure I did it all the way correctly when I have a spare moment!

**Comment by ecwillis** [comment] 2019-06-06 21:06
As I reference ... I believe this is what is happening behind the scenes ...

```
const crypto = require('crypto');
const secret = 'lkjsadhfkjhasdfq29784yhjkdsfg';
const body = '{ "one": 1, "two": "deu" }';

const buf1 = Buffer.from(body);
const hash1 = crypto.createHmac('sha256', secret).update(buf1).digest('base64');

const bodyObj = JSON.parse(body);

const buf2 = Buffer.from(JSON.stringify(bodyObj));
const hash2 = crypto.createHmac('sha256', secret).update(buf2).digest('base64');


console.log(hash1);
console.log(hash2);
```

Output:
```
MzA4yGKzA8mYDsZrUHQ39rI07eVNnkhQ60eMSQwPuGc=
MDSzRxcpUUGd1Qc7XXMWNOrBh7ad1d2n3fNK2nWZrpo=
```

**Comment by ryanblock** [comment] 2019-06-06 21:27
Ah, if so, what's probably happening is Shopify is encoding on the way out with some other language's parser, adding spacing to their JSON payload instead of condensing it. Per your example, you can see the difference between the contents of `buf1` and the pre-buffered `buf2`:
```
{ "one": 1, "two": "deu" }
{"one":1,"two":"deu"}
```
Those would ofc come out the other side differently, hence your issue. If that is indeed what Shopify is doing, that's annoying as hell – they should be sending fully condensed JSON to avoid this kind of an issue for folks.

You could try to protect against it by recreating that format with some splitting and joining like `JSON.stringify(req.body,null,1).split('\n').join('').split('}').join(' }')` (and so on and so forth) but that may require some fiddling.

**Comment by ryanblock** [comment] 2019-06-11 15:51
Just wanted to check back, any luck on this?

**Comment by brianleroux** [comment] 2019-07-06 19:17
closing this out; architect 6.x we have moved to cloudformation and aws_proxy style integration which possibly could fix this issue! you can read more about those payloads here: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format

**Closed by brianleroux** 2019-07-06 19:17 UTC
