### ISSUE TITLE
Ability to set headers (particularly cache-control) in @static

### ISSUE THREAD

**Issue by ryanflorence** [architect/architect#1106] opened 2021-03-28 16:40 UTC
I'm trying to build the starter template for Remix (https://remix.run) apps deployed with Architect. While Architect supports fingerprinting, Remix already fingerprints all the assets that go into the @static directory. I'd like a way to set headers on those responses.

On other platforms you can supply a `headers` config on static assets. I'm not well versed in the *.arc syntax so forgive my naive example, but I'd love to be able to do this:

```
@static
headers
  cache-control: public, max-age=31540000000
```

Using `fingerprint true` is problematic for Remix because we take a single JavaScript file that includes both server side and client side exports and split it up into two builds: server and client. Our server bundle has already considered the public path to assets at build time and included it in the bundle. This means it's too late (or at least really awkward) for us to use `arc.static("filename.js")` at runtime, we've already got the fingerprinted asset urls in the bundle.

Another alternative I've thought of doing is simply adding my own http function for static assets and then I've got control over my headers, but it seems silly to dance around architect's static feature.

Being able to set headers on the static folder in `app.arc` would make this simple.

I agree with @ryanblock's [comments](https://github.com/architect/architect/issues/332#issuecomment-472506738) about setting a longer max-age on assets by default:

> I weighed that pattern (which makes total sense as a best practice) against the dangers inherent of setting a new default.
> ... In other words, is it safe to always assume fingerprinting? Sadly, although everything should be doing it, I don't think it can be assumed 

I agree we shouldn't assume people are fingerprinting static assets, but when I am, I'd like to be able to take control of my static asset cache headers.

Finally, we're hoping to use Architect for the official public Remix docs, so I'd love to be able to control my own static asset headers to that end :)

**Comment by ryanblock** [comment] 2021-03-28 19:32
We can do this! Not at my desk rn but it's possible to completely customize static asset logic. Stand by, will check back later today.

**Comment by ryanblock** [comment] 2021-03-28 23:15
Ok, so I did a quick look at our docs and sure enough, the feature I think you need is apparently undocumented. We suck. Onward!

Try this:
```
@static
fingerprint external
```

Fingerprint `true` uses Architect's built-in fingerprinter, whereas `external` assumes your app has handled its own fingerprinting, and as such doesn't mutate any filenames or write and static manifests, but does indeed set long-lived cache headers.

That doesn't give you full control of your static asset cache headers, but assuming the reason you want control of those headers is to ensure that your already fingerprinted assets are getting long-lived clientside caching, we got you covered on that.

Also: stoked about you using Architect for Reminx, please let us know if there's anything we can do to help enable that? Happy to advise, consult, or send PRs, we've gotten pretty decent at building docs sites with Arc (albeit our content clearly has room for improvement, ahem).

**Comment by ryanflorence** [comment] 2021-03-31 23:42
Oh that's excellent!

For some CDNs its nice to be able to set `Surrogate-Control` and `Surrogate-Key` but I can't really think of any reason to use those for static assets.

Thanks!

> albeit our content clearly has room for improvement

Everybody's stuff is twice as awesome as their docs indicate. It's a struggle!

**Comment by ryanflorence** [comment] 2021-04-01 00:33
Hmm, I'm not seeing any long term headers here:

https://fsvxw2m9z4.execute-api.us-west-2.amazonaws.com/_static/build/entry.client-EXP6DJPT.js

**Comment by ryanblock** [comment] 2021-04-01 00:38
That is likely because when we publish files to S3, we check to see if they already exist and the checksums match. If so, we do not republish them. So I'm guessing that file already existed. If you jump into your S3 bucket and clear out those asses and re-publish them, you should get the headers.

**Comment by brianleroux** [comment] 2021-04-01 01:04
Reopening while we verify if this fix works...and a question: do we think the behavior should be consistent/deterministic always set or even reset when deploying (?)

**Comment by ryanblock** [comment] 2021-04-01 03:02
I can confirm that what I mentioned above is what is happening. Here's a js file I loaded without fingerprinting:
<img src="https://user-images.githubusercontent.com/200964/113237294-6c34a200-925b-11eb-9521-0842fcb21d14.png" width=300>
Here's what happens when I enable `external`:
<img src="https://user-images.githubusercontent.com/200964/113237390-98502300-925b-11eb-8425-5bb0f345de2f.png" width=500>
Same headers on reload. Then I follow my above instructions, and:
<img src="https://user-images.githubusercontent.com/200964/113237542-e107dc00-925b-11eb-965d-cd6f856d09cf.png" width=300>

Re-closing, but we should def open a new issue for ensuring static asset headers are always correct to the current `fingerprint` setting.

**Closed** 2021-04-01 03:03 UTC

**Comment by ryanblock** [comment] 2021-04-01 03:40
Should be fixed in https://github.com/architect/deploy/pull/305!

**Comment by ryanflorence** [comment] 2021-04-01 04:49
Beautiful, thanks folks!

![image](https://user-images.githubusercontent.com/100200/113245036-018b6280-926b-11eb-9324-a8ecfb798bb5.png)
