### ISSUE TITLE
request.body is encoded

### ISSUE THREAD

**Issue by jeremyhodges** [architect/architect#1075] opened 2021-02-22 18:08 UTC
**Describe the issue**
I have created a basic @architect site with a POST endpoint. When I run the sandbox and use postman to make a POST to the endpoint and pass in data, the value within request.body appears to be encoded. This means that something like `request.body.email` does not work. When I view the example sites, the examples do not appear to be doing any type of decoding and can directly access the values of the body as properties of the body object. Have I missed an application or middleware setting?

**Steps to reproduce**
1. Setup a new @architect site
2. Create a new HTTP POST endpoint
3. Use Postman to hit the endpoint passing in either JSON data in the body or `form-data`
4. Try returning `request.body` and look at the results in Postman

**Expected behavior**
I would expect that if I pass `form-data` with a key-value pair that I can access that data as part of the `request.body` object. 

**Screenshots**
<img width="344" alt="Screen Shot 2021-02-22 at 1 06 17 PM" src="https://user-images.githubusercontent.com/204691/108750310-dc3e6280-750e-11eb-9728-4789f1007705.png">
<img width="713" alt="Screen Shot 2021-02-22 at 1 06 09 PM" src="https://user-images.githubusercontent.com/204691/108750324-e1031680-750e-11eb-8584-9c5f822a94fb.png">
<img width="911" alt="Screen Shot 2021-02-22 at 1 05 57 PM" src="https://user-images.githubusercontent.com/204691/108750337-e3657080-750e-11eb-9841-58284e4a6002.png">

**Desktop**
Please complete the following information (if appropriate):
 - OS: MacOS X
 - Browser: Postman 8.0

**Comment by brianleroux** [comment] 2021-02-22 18:11
Hey Jeremy! This is expected behavior of API Gateway payloads. We have runtime helpers in `@architect/functions` to decode that body (or if you prefer you can do that yourself.)

Change line 3 to read: `exports.handler = arc.http.async(http)` and move the 'http' function definition below. The body will be automatically decoded by the architect/functions middleware. Closing for now but if you have further questions please don't hesitate to ask!

**Closed by brianleroux** 2021-02-22 18:11 UTC

**Comment by jeremyhodges** [comment] 2021-02-22 19:23
I figured I was missing something. Looks like `arc.middleware` is just a backward compatible way to call `arc.http.async`, correct?

I still don't appear to be getting the decoded value. Assume I am still missing something obvious.

<img width="854" alt="Screen Shot 2021-02-22 at 2 18 36 PM" src="https://user-images.githubusercontent.com/204691/108758614-4e1ba980-7519-11eb-9abf-7e0af1d24837.png">
<img width="715" alt="Screen Shot 2021-02-22 at 2 18 46 PM" src="https://user-images.githubusercontent.com/204691/108758618-4eb44000-7519-11eb-9b2a-d9b11e75f3f0.png">
<img width="871" alt="Screen Shot 2021-02-22 at 2 19 13 PM" src="https://user-images.githubusercontent.com/204691/108758621-4eb44000-7519-11eb-8baa-e420d731f1d2.png">
<img width="733" alt="Screen Shot 2021-02-22 at 2 19 21 PM" src="https://user-images.githubusercontent.com/204691/108758624-4eb44000-7519-11eb-98de-b2ed756393a9.png">

**Comment by brianleroux** [comment] 2021-02-22 20:02
what happens when the code reads like this?

```javascript
let arc = require('@architect/functions')
exports.handler = arc.http.async(r=> ({ req: r }))
```

(pls paste in responses and code in text if possible! quicker for me to repro)

**Comment by jeremyhodges** [comment] 2021-02-22 20:08
> what happens when the code reads like this?
> 
> ```js
> let arc = require('@architect/functions')
> exports.handler = arc.http.async(r=> ({ req: r }))
> ```
> 
> (pls paste in responses and code in text if possible! quicker for me to repro)

Starting to think it has something to do with my Postman setup. Here's the response:

```
{
    "req": {
        "version": "2.0",
        "routeKey": "POST /person",
        "rawPath": "/person",
        "rawQueryString": "",
        "headers": {
            "user-agent": "PostmanRuntime/7.26.10",
            "accept": "*/*",
            "postman-token": "a5bb626e-f5b5-47fa-aafb-0df3c88e743b",
            "host": "localhost:3333",
            "accept-encoding": "gzip, deflate, br",
            "content-type": "multipart/form-data; boundary=--------------------------875501449660867770364556",
            "content-length": "165"
        },
        "requestContext": {
            "http": {
                "method": "POST",
                "path": "/person"
            },
            "routeKey": "POST /person"
        },
        "body": {
            "base64": "LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLTg3NTUwMTQ0OTY2MDg2Nzc3MDM2NDU1Ng0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJuYW1lIg0KDQpKZXJlbXkNCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS04NzU1MDE0NDk2NjA4Njc3NzAzNjQ1NTYtLQ0K"
        },
        "isBase64Encoded": true,
        "session": {},
        "httpMethod": "POST",
        "pathParameters": {},
        "queryStringParameters": {},
        "resource": "/person",
        "method": "POST",
        "params": {},
        "query": {}
    }
}
```

**Comment by brianleroux** [comment] 2021-02-22 20:11
maybe idk! here's a quick url for testing with it: https://cookie-oz5-staging.begin.app (same code as above)

I ran `curl -X POST -d 'foo=bar' https://cookie-oz5-staging.begin.app`

```
{"req":{"version":"2.0","routeKey":"ANY /","rawPath":"/","rawQueryString":"","headers":{"accept":"*/*","content-length":"7","content-type":"application/x-www-form-urlencoded","host":"cookie-oz5-staging.begin.app","user-agent":"curl/7.64.1","x-amzn-trace-id":"Root=1-60340fc5-10fa2f137d965cd518f28e9d","x-forwarded-for":"173.180.195.26","x-forwarded-port":"443","x-forwarded-proto":"https"},"requestContext":{"accountId":"629375599532","apiId":"05a4xg8364","domainName":"cookie-oz5-staging.begin.app","domainPrefix":"cookie-oz5-staging","http":{"method":"POST","path":"/","protocol":"HTTP/1.1","sourceIp":"173.180.195.26","userAgent":"curl/7.64.1"},"requestId":"bKdm6hupCYcEMzQ=","routeKey":"ANY /","stage":"$default","time":"22/Feb/2021:20:10:45 +0000","timeEpoch":1614024645773},"body":{"foo":"bar"},"isBase64Encoded":true,"session":{},"httpMethod":"POST","pathParameters":{},"queryStringParameters":{},"resource":"/","method":"POST","params":{},"query":{}}
```

**Comment by jeremyhodges** [comment] 2021-02-22 20:25
OK, something with my Postman setup for sure. If I hit your Url provided with postman I get:

```
{
    "req": {
        "version": "2.0",
        "routeKey": "ANY /",
        "rawPath": "/",
        "rawQueryString": "",
        "headers": {
            "accept": "*/*",
            "accept-encoding": "gzip, deflate, br",
            "content-length": "165",
            "content-type": "multipart/form-data; boundary=--------------------------085476225006819466910858",
            "host": "cookie-oz5-staging.begin.app",
            "postman-token": "34612a67-ba31-47c6-81b3-4adb332bb489",
            "user-agent": "PostmanRuntime/7.26.10",
            "x-amzn-trace-id": "Root=1-60341197-4f3862832506922c147ffc5f",
            "x-forwarded-for": "174.194.23.61",
            "x-forwarded-port": "443",
            "x-forwarded-proto": "https"
        },
        "requestContext": {
            "accountId": "629375599532",
            "apiId": "05a4xg8364",
            "domainName": "cookie-oz5-staging.begin.app",
            "domainPrefix": "cookie-oz5-staging",
            "http": {
                "method": "POST",
                "path": "/",
                "protocol": "HTTP/1.1",
                "sourceIp": "174.194.23.61",
                "userAgent": "PostmanRuntime/7.26.10"
            },
            "requestId": "bKevpgi2iYcEPgg=",
            "routeKey": "ANY /",
            "stage": "$default",
            "time": "22/Feb/2021:20:18:31 +0000",
            "timeEpoch": 1614025111278
        },
        "body": {
            "base64": "LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLTA4NTQ3NjIyNTAwNjgxOTQ2NjkxMDg1OA0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJuYW1lIg0KDQpKZXJlbXkNCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0wODU0NzYyMjUwMDY4MTk0NjY5MTA4NTgtLQ0K"
        },
        "isBase64Encoded": true,
        "session": {},
        "httpMethod": "POST",
        "pathParameters": {},
        "queryStringParameters": {},
        "resource": "/",
        "method": "POST",
        "params": {},
        "query": {}
    }
}
```

If I hit my local URL with CURL `curl -X POST -d 'name=jeremy' http://localhost:3333/person` I get the expected response: 

`{"status":"success","person":{"name":"JEREMY"}}`

At first I thought it was the `content-type` in the headers as Postman seems to add this `; boundary=` but I hard coded the content type to `multipart/form-data` and still get the same results. I'll keep playing with the `bodyParser` and see if I can determine what in the Postman setup is causing the different results.

**Comment by brianleroux** [comment] 2021-02-22 20:35
I don't know much about Postman but could be a good opportunity to start writing tests to shake out the expected/desired behavior. I usually use `tape`, `tap-spec` and `tiny-json-http` for making requests against `@architect/sandbox` locally. There's more in the docs for doing this here https://arc.codes/docs/en/guides/developer-experience/local-development

**Comment by filmaj** [comment] 2021-02-22 22:01
I'ma jump in on the fun!

I can reproduce the issue if I use the `multipart/form-data' content-type header with curl. Here's my function:

```
let arc = require('@architect/functions')
exports.handler = arc.http.async(r=> ({
  headers: {
    'content-type': 'application/json'
  },
  body: JSON.stringify({
    body: r.body,
    headers: r.headers
  }, null, 2)
}))
```

And some `curl` results:

```
➜ curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d 'foo=bar' http://localhost:3333/
{
  "body": {
    "foo": "bar"
  },
  "headers": {
    "host": "localhost:3333",
    "user-agent": "curl/7.64.1",
    "accept": "*/*",
    "content-type": "application/x-www-form-urlencoded",
    "content-length": "7"
  }
}%

➜ curl -X POST -H 'Content-Type: multipart/form-data' -d 'foo=bar' http://localhost:3333/
{
  "body": {
    "base64": "Zm9vPWJhcg=="
  },
  "headers": {
    "host": "localhost:3333",
    "user-agent": "curl/7.64.1",
    "accept": "*/*",
    "content-type": "multipart/form-data",
    "content-length": "7"
  }
}%
```

It looks like [`sandbox` assumes that a `multipart/form-data` content-type means the request body is binary, and thus base64 encodes it](https://github.com/architect/sandbox/blob/master/src/http/middleware/_binary-handler.js#L14-L20). By the time that HTTP request gets through sandbox and is picked up by [`@architect/functions`' body parser module, it also assumes a multipart/form-data content type means binary, so leaves it as base64 and doesn't parse it](https://github.com/architect/functions/blob/master/src/http/helpers/body-parser.js#L46). Compare that to what [`@architect/functions` does with `application/x-www-form-urlencoded` request, where it will actually parse the body, so you end up getting a nice JSON object as the body](https://github.com/architect/functions/blob/master/src/http/helpers/body-parser.js#L41-L44).

**Comment by jeremyhodges** [comment] 2021-02-22 22:08
@filmaj : You're absolutely right. Thanks for the kick in the head. My brain was not working today and I totally forgot that `multipart/form-data` header is going to be used when uploading files, etc. from the form and it's `application/x-www-form-urlencoded` which is used for most form submissions. This makes absolute sense now how the `bodyParser` helper is working and the base64 value is provided with the `multipart/form-data` header type.

Thanks to @brianleroux as well. Using the `http.async` function is really what I was missing. Once using that, the framework is absolutely functioning as you'd expect it to.

**Comment by ryanblock** [comment] 2021-02-22 22:09
Which version of Architect is this running out of curiosity? The check for `request.body.base64` and putting that as a named param inside a body object is pretty old (Arc 5-era), may be time to rethink this code path.
