### ISSUE TITLE
`npx arc deploy -d src/path/to/lambda` no workie

### ISSUE THREAD

**Issue by filmaj** [architect/architect#1469] opened 2023-12-29 19:43 UTC
**Describe the issue**
 
`-d` just does a full deploy. according to CLI docs and arc.codes, it should do a direct deploy.

`--direct` works fine, though.

using arc 10.16.3

**Comment by ryanblock** [comment] 2024-02-02 04:10
Duplicate of https://github.com/architect/architect/issues/1350; updated docs for Arc 11 release!

**Closed by ryanblock** 2024-02-02 04:10 UTC
