### ISSUE TITLE
add ability to deploy to different stacknames

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#429] opened 2019-08-22 18:54 UTC
currently architect has first class support local dev, staging and production environments. staging and production are just cloudformation stacks and we should expose a cli option to deploy to an arbitrary stackname.

Given an app named `myapp` running `arc deploy stack foo` should deploy a stack named `MyappFoo`. 

> Note: these arbitrary stacks should be `NODE_ENV='staging'` … the 'essential complexity of staged delivery is 'test/local', 'staging' and 'production' and this is def just another aspect of 'staging' in this spirit

**Comment by ryanblock** [comment] 2019-08-22 21:40
Dupe of https://github.com/architect/architect/issues/376

**Comment by jgallen23** [comment] 2019-09-26 19:22
Another approach that might be less intrusive is to be able to override the app name with an env var.

something like `ARC_APPNAME=myappfoo arc deploy` would override `myapp` everywhere.  

To simplify the impact, the change could be made on the parser level.  Before returning the `arc` object, it does a check if the env var exists and sets.  That way all the `arc.app[0]` everwhere would continue to work. (side note, it would be awesome to be able to override anything in the .arc file from an ENV var)

This has additional benefits if you wanted to spin up an alternate production environment, you could still just `ARC_APPNAME=myappalt arc deploy production`.  Might be useful for blue/green deployments or if you wanted to send a % of traffic to the other prod environment

**Comment by jgallen23** [comment] 2019-09-30 18:59
the override could be done in the `read-arc` util here: https://github.com/architect/utils/blob/master/read-arc.js#L52.

**Comment by jgallen23** [comment] 2019-09-30 18:59
If you are good with that approach, let me know and I can spin up a PR

**Comment by ryanblock** [comment] 2019-09-30 19:11
I may be wrong, but I think this will take a good deal of investigation and consideration than overwriting the app name. We are definitely 100% going to do this, it's mostly just a matter of figuring out the best way.

If you'd like to do a deeper dive into how [`package`](https://github.com/architect/package), [`inventory`](https://github.com/architect/utils/blob/master/inventory.js), and [`deploy`](https://github.com/architect/deploy) interact, while keeping in mind Arc 6 service reflection via SSM ([example here](https://github.com/architect/functions/blob/master/src/tables/lookup-tables.js)), imo that'd be a great place to start!

**Comment by brianleroux** [comment] 2019-09-30 19:12
Think it's safer to make a part of deploy since this is pretty specific to the AWS implementation and not the arcfile grammar/parsing

**Comment by jgallen23** [comment] 2019-09-30 19:14
Yeah, that makes sense - I might just fork deploy and see if it works for us.  We have a fully stateless app, so we don't have to worry about dynamo tables.  Probably gets a bit gnarlier if you use dynamo

**Comment by ryanblock** [comment] 2019-09-30 19:17
Since this is a dupe of #376 and should have been closed already, will keep that one open and continue our conversation there.

It's very much on my list though!

**Closed by ryanblock** 2019-09-30 19:17 UTC
