### ISSUE TITLE
Segfault when using an ESM plugin and @architect/sandbox in a jest unit test

### ISSUE THREAD

**Issue by lpsinger** [architect/architect#1448] opened 2023-08-31 18:23 UTC
**Describe the issue**
In an Architect project that contains one or more ESM plugins, if you use `@architect/sandbox` in a [Jest](https://jestjs.io) unit test, it segfaults.

**Steps to reproduce**
See minimal reproducer at https://github.com/lpsinger/arc-jest-segfault-reproducer. It has a minimal ESM plugin [src/plugins/plugin-foo.mjs](https://github.com/lpsinger/arc-jest-segfault-reproducer/blob/main/src/plugins/plugin-foo.mjs) and a toy Jest test [test.js](https://github.com/lpsinger/arc-jest-segfault-reproducer/blob/main/test.js).

To run:
```
git clone https://github.com/lpsinger/arc-jest-segfault-reproducer
cd arc-jest-segfault-reproducer
npm i
npm run test
```

**Expected behavior**
`npm run test` should exit normally without errors.

**Actual behavior**
The output of `npm run test` is:

```
> arc-jest-segfault-reproducer@0.0.0 test
> jest


 RUNS  ./test.js
Segmentation fault: 11
```

**Desktop**
Please complete the following information (if appropriate):
 - OS: macOS, Linux
 - Browser N/A
 - Version N/A

**Mobile**
N/A

**Additional context**
If you disable the plugin by commenting it out in `app.arc`, or if you replace the plugin source [src/plugins/plugin-foo.mjs](https://github.com/lpsinger/arc-jest-segfault-reproducer/blob/main/src/plugins/plugin-foo.mjs) with an empty file, or if you rename the plugin to `src/plugin/plugin-foo.js` and convert it to CommonJS, then the tests pass.

**Comment by ryanblock** [comment] 2023-08-31 21:24
Thanks for the repro case! Definitely the nicest way to start on a bug. In this case, I don't believe the issue is Architect's. Here's the offending line when run in Jest: https://github.com/architect/inventory/blob/main/src/config/pragmas/plugins.js#L62

This is blowing up because Jest doesn't yet properly support ESM, per: https://jestjs.io/docs/ecmascript-modules

Jest is notorious for clobbering globals and rewriting core Node.js functionality; in this case, it looks like it's blowing up Node's module loading system (which is already admittedly funky). We generally advise against using it for these reasons (and many more).

That said, we also understand that despite those concerns, folks do still use Jest, and we've invested quite a but of time making sure that Architect stuff does work with it. If you can think of how we can get things working correctly in this case, I'm all ears!

**Comment by lpsinger** [comment] 2023-08-31 22:20
Do you have a different JavaScript testing framework that you suggest instead? The Remix community seems to favor jest.

**Comment by ryanblock** [comment] 2023-09-01 03:10
At the risk of sounding pedantic, I generally try to avoid testing frameworks, as they tend to wind up in places like Jest, where it's mutating the execution environment, impacting the reliability and determinism of your tests.

For everything in Architect-land (and most of our closed-source work) we rely on [`tape`](https://www.npmjs.com/package/tape), which is a very fast, lightweight, and reliable TAP-compatible harness/runner. Hope that helps!

**Comment by ryanblock** [comment] 2023-09-03 19:58
Going to close this, but please do reopen if we think there's something else Architect can be doing to alleviate this issue!

**Closed by ryanblock** 2023-09-03 19:58 UTC
