### ISSUE TITLE
Feature request: surgical deploys (single lambda)

### ISSUE THREAD

**Issue by mikemaccana** [architect/architect#487] opened 2019-10-12 16:58 UTC
This was super cool, and mentioned by Brian in his older Arc talks, but it didn't make the original release of arc 6. It would be good to have back!

`arc deploy production http/get-index` or similar.

**Comment by ryanblock** [comment] 2019-10-12 16:59
Dupe of https://github.com/architect/deploy/issues/5 (and yes, I'd really like this back!)

**Closed by ryanblock** 2019-10-12 16:59 UTC
