### ISSUE TITLE
Rehydration takes ~30 seconds on Ubuntu 20.04 on an XFS filesystem, many files touched

### ISSUE THREAD

**Issue by jzohrab** [architect/architect#908] opened 2020-07-09 18:59 UTC
**Describe the issue**

Our project (Li, https://github.com/covidatlas/li) uses Architect.  Our src/shared is lightweight.  @joliss noted that hydration was taking forever on her machine, and opened https://github.com/covidatlas/li/issues/301 describing the problem.

I've confirmed on my mac that calling `npm start` on my Mac results in ~10K files being logged as 'updated', using the following script in our project root:

```
$ cat node-watch-test.js 
let watch = require('node-watch')
let watcher = watch('.', { recursive: true })
watcher.on('change', function (event, fileName) {
    console.log(event, fileName)
})
```

**Steps to reproduce**

* Put the above file in your project root
* In one window, run `$ node node-watch-test.js > ~/watch`
* In another window, start your arc server: `$ arc sandbox`
* see the giant file `~/watch` which contains all node_module files as well as project files

**Expected behavior**

Only files actually changed should be listed

**Comment by ryanblock** [comment] 2020-07-09 20:45
I did this and saw ~4k files changed. On my computer (a relatively recent Mac with an SSD) Sandbox took under 2 seconds to start:
```
> arc sandbox

         App ⌁ li
      Region ⌁ us-west-1
     Profile ⌁ covidatlas
     Version ⌁ Architect 6.4.0
         cwd ⌁ /li

✓ Sandbox Found Architect project manifest, starting up
✓ Startup Populating process.env with .arc-env @testing
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with src/shared
✓ Sandbox Project files hydrated into functions
✓ Sandbox @tables created in local database
✓ Sandbox @events and @queues ready on local event bus
✓ Sandbox Loaded routes
    get /get/normal ....................... get-get-normal
    get /get/headless ..................... get-get-headless
    get /locations ........................ get-locations
    get /locations/:location .............. get-locations-000location

✓ Sandbox Started in 1373ms
✈︎ Local environment ready!

    http://localhost:3333
```

So it sounds like there are two concerns based on https://github.com/covidatlas/li/issues/301:

**Comment by ryanblock** [comment] 2020-07-09 21:01
I did this and saw ~4k files logged by the filesystem watcher script above. On my computer (a relatively recent Mac with an SSD) Sandbox took under 2 seconds:
```
> arc sandbox

         App ⌁ li
      Region ⌁ us-west-1
     Profile ⌁ covidatlas
     Version ⌁ Architect 6.4.0
         cwd ⌁ /li

✓ Sandbox Found Architect project manifest, starting up
✓ Startup Populating process.env with .arc-env @testing
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with src/shared
✓ Sandbox Project files hydrated into functions
✓ Sandbox @tables created in local database
✓ Sandbox @events and @queues ready on local event bus
✓ Sandbox Loaded routes
    get /get/normal ....................... get-get-normal
    get /get/headless ..................... get-get-headless
    get /locations ........................ get-locations
    get /locations/:location .............. get-locations-000location

✓ Sandbox Started in 1373ms
✈︎ Local environment ready!

    http://localhost:3333
```

So it sounds like there are two concerns based on https://github.com/covidatlas/li/issues/301:
1. There are a lot of filesystem operations when starting the Sandbox
2. It is taking a while to start

(If I don't have that right, please let me know? /cc @joliss)

Re. 1: Sandbox has to make sure shared code is available to every Lambda function. Individual functions would can opt-out of getting shared files; in their `.arc-config` file by adding:
```
@arc
shared false
```
This, of course, means that function will no longer have any files from `src/shared`, so take care when using this feature, as any reliance on shared code will now fail.

Another way to reduce the number of files being moved around during hydration is to reduce the number dependencies in `src/shared/node_modules`. I don't think there's much to remove from the Li project, as it was already pretty lean.

Finally, there's note that Sandbox may be performing unnecessary disk operations (`Expected behavior / Only files actually changed should be listed`); upon startup, how should startup determine whether a given function needs to be hydrated with shared files?

It could create a hash map of all files in src/shared (for example), then compare file contents to the files present in every function, and copy any over that differ. Doing so would be enormously more complex than just overwriting the existing destination directory, and would result in at least as many file operations, if not more.

Re. 2: See the above notes re. perf, although I'm still fuzzy on what's going on, and could use some more information. 30 seconds to start Sandbox isn't ideal, especially for a project of this size. I'm able to get it started in under 2 seconds, so it sounds like maybe there's something else going on.

Related, I'm not sure how `FSWatcher._handle.onchange` events factor in here. Sandbox's filesystem watcher only starts after initial hydration has taken place (see: https://github.com/architect/sandbox/blob/master/src/cli/index.js#L116), so is it possible there was another sandbox already running in the project directory that may have been slowing down startup? This needs more information to diagnose.

Thanks!

**Comment by ryanblock** [comment] 2020-07-16 02:18
Bump! Any thoughts here?

**Comment by joliss** [comment] 2020-07-20 18:27
Sorry it took me forever to respond! So, let me back up a step and explain the problem, and what I think the cause is.

So on my Linux VM, initial hydration is fine, but rehydration (after a file has changed) is very slow (30+ seconds). On the macOS host, both are fast.

I tried tracking down where all the time is spent, and it turned out that a lot of onChange events were being fired:

<img width="1917" alt="DevTools - Node js ilzhh" src="https://user-images.githubusercontent.com/524783/87971539-688e3000-cabd-11ea-89db-bc6a50623389.png">

So I decided to dig into what's causing all those onChange events to fire, by adding the following line to `@architect/sandbox`:

```diff
src/architect-sandbox $ git diff
diff --git src/cli/index.js src/cli/index.js
index 7465892..79f47b2 100644
--- src/cli/index.js
+++ src/cli/index.js
@@ -114,6 +114,7 @@ module.exports = function cli (params = {}, callback) {
      * Watch for pertinent filesystem changes
      */
     watcher.on('change', function (event, fileName) {
+      console.log(event, fileName)

       if (!paused && fs.existsSync(pauseFile)) {
         paused = true
```

When I `npm link`'ed my copy of `@architect/sandbox` into Li, it showed a flood of changes. The `node-watch-test.js` in the original post reproduces this more easily.

So what seems to be happening is that for some reason, a lot of files are being written to somehow by the sandbox process. On macOS, this also happens, but it doesn't have as catastrophic a performance impact as on Linux.

I'm not sure why all those files are being written to. My assumption is that "(re)hydration" means (re)reading the module files and creating a set of in-memory function objects -- is this wrong?

So for example, let's take the first `.js` file from my [list of files for which the onChange event fired](https://gist.github.com/joliss/3ac7a9fe64ca35927f25d5dcb786ac55):

```
update src/http/get-get-normal/node_modules/@architect/shared/cache/_convert-timestamp.js
```

It makes sense to me that this file would have to be *read*. But is there a reason why it's being written to somehow? Or if that's not supposed to be happening, do you have any idea what could be causing this?

**Comment by ryanblock** [comment] 2020-07-21 22:53
I think this may have to do with running in a VM. I'm unable to replicate this behavior working natively, and the same appears to be true for you as well (`On the macOS host, both are fast.`).

First, to answer your questions: rehydration refers to the Sandbox local dev server handling shared code and dependencies. If you change a file in `src/shared`, Sandbox copies the updated `src/shared` folder to all child functions, so everything is sure to have the latest copy of what's in `src/shared`. That is the source of your filesystem events.

Copying everything, and not just the file or files that changed is not incredibly efficient, but keeping a ledger of which files changed and rehydrating those is a potential bug vector; the copy-everything path has proven to be highly reliable, and on modern machines even the largest projects are pretty performant.

Sounds like maybe the source of this confusion in this issue is related to not being fully up to speed on what's happening under the hood?

Anyway, how I tested:
- Locally I added a simple counter to the Sandbox CLI (diff lines may be slightly different as I pulled this from the latest version of Sandbox, but there should be no substantive changes related to this issue):
```diff
diff --git a/src/cli/index.js b/src/cli/index.js
index 7465892..a85b17f 100644
--- a/src/cli/index.js
+++ b/src/cli/index.js
@@ -65,6 +65,8 @@ module.exports = function cli (params = {}, callback) {
     }
     let paused = false

+    let counter = 0
+
     // Rehydrator
     function rehydrate ({ timer, only, msg }) {
       lastEvent = Date.now()
@@ -76,6 +78,7 @@ module.exports = function cli (params = {}, callback) {
         hydrate.shared({ only }, () => {
           let end = Date.now()
           update.done(`Files rehydrated into functions in ${end - start}ms`)
+          console.log(`Observed ${counter} total file watcher events`)
         })
       }, 50)
     }
@@ -114,6 +117,7 @@ module.exports = function cli (params = {}, callback) {
      * Watch for pertinent filesystem changes
      */
     watcher.on('change', function (event, fileName) {
+      counter++

       if (!paused && fs.existsSync(pauseFile)) {
         paused = true
```
- Started Li in the Sandbox on my local machine (not in a VM)
- Changed a shared file a few times
- Got roughly 6-8K filesystem events each time:
```
[7/21/2020, 3:38:52 PM]
⚬ Sandbox Shared file changed, rehydrating functions...
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with src/shared
✓ Sandbox Files rehydrated into functions in 1655ms
Observed 6580 total file watcher events

[7/21/2020, 3:38:55 PM]
⚬ Sandbox Shared file changed, rehydrating functions...
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with src/shared
✓ Sandbox Files rehydrated into functions in 1557ms
Observed 12812 total file watcher events

[7/21/2020, 3:39:38 PM]
⚬ Sandbox Shared file changed, rehydrating functions...
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with src/shared
✓ Sandbox Files rehydrated into functions in 1652ms
Observed 21009 total file watcher events

[7/21/2020, 3:40:34 PM]
⚬ Sandbox Shared file changed, rehydrating functions...
⚬ Hydrate Hydrating app with shared files
✓ Hydrate Hydrated app with src/shared
✓ Sandbox Files rehydrated into functions in 1511ms
Observed 27434 total file watcher events
```

This project's `src/shared` dir contains a total of about 360 files, and ~16 functions – this would result in ~6K file copy operations per mutation, which looks roughly in line with those numbers.

My suspicion is that whatever VM software you're using is doubling up on filesystem requests (or is otherwise exposing inefficiencies with the way it handles filesystem operations).

Since I'm still not clear on what the actual Sandbox issue is here, I'd like to close this issue unless there are any objections or specific repro steps for bugs.

Related, I'm open to potentially creating a new enhancement for hydration that deals in hydrating individual files (that module is here: https://github.com/architect/hydrate) instead of everything in `src/shared`. I assume that would be both a new method for `@architect/hydrate`, as well as some kind of debouncing + batching system for running that method from the CLI. Any interest in a PR?

**Comment by joliss** [comment] 2020-07-27 19:00
> First, to answer your questions: rehydration refers to the Sandbox local dev server handling shared code and dependencies. If you change a file in src/shared, Sandbox copies the updated src/shared folder to all child functions, so everything is sure to have the latest copy of what's in src/shared. That is the source of your filesystem events.

You saw my other PR at https://github.com/architect/hydrate/pull/108 already, but just wanted to say thanks for explaining so patiently. This helped clear up my confusion!

I think https://github.com/architect/hydrate/pull/108 addresses this adequately, so we can probably close this issue.

**Comment by filmaj** [comment] 2020-11-16 03:58
Gonna close this; hope the symlink solution helped!

**Closed by filmaj** 2020-11-16 03:58 UTC
